// Tous les textes de l'interface, en français et en anglais. Les titres, catégories
// et identifiants d'étagères restent ceux du jeu (anglais) dans les deux langues.

export type Langue = 'fr' | 'en'

export const TEXTES = {
  fr: {
    titre: 'Arcane Library Shelf Trainer',
    sousTitre: 'Apprenez l’étagère et la série de chaque livre, pour le speedrun',
    jeu: 'Librarian: Tidy Up the Arcane Library!',
    jaugePlan: 'Plan',
    jaugeLivres: 'Livres',
    jaugeTomes: 'Tomes',
    jaugeEtageres: 'Étagères',
    etagere: 'Étagère',
    exactEtagere: (titre: string) => `Exact : « ${titre} »`,
    fauteEtagere: (titreChoisi: string, section: string, categorie: string, titreAttendu: string) =>
      `Non : « ${titreChoisi} » est en ${section} (${categorie}). C’était « ${titreAttendu} »`,
    raccourcisEtagere: 'Clavier : 1 à 4.',
    modes: {
      plan: { nom: 'Plan', aide: 'Une catégorie : quelle étagère ?' },
      situer: { nom: 'Situer', aide: 'Un identifiant : où est cette étagère, de mémoire ?' },
      livres: { nom: 'Livres', aide: 'Un livre : quelle étagère ?' },
      etagere: { nom: 'Étagère', aide: 'Une étagère : lequel de ces livres y est rangé ?' },
      tomes: { nom: 'Tomes', aide: 'Un livre : combien de tomes dans la série ?' },
      chrono: { nom: 'Chrono', aide: 'Des livres contre la montre' },
    },
    filtres: { tous: 'Les deux étages', '1': 'Étage 1', '2': 'Étage 2' },
    filtreTomes: 'Séries',
    tousLesTomes: 'Toutes',
    tomesPastille: (n: number) => `${n} tomes`,
    sep: ' : ',
    enJeu: 'En jeu',
    accueilTitre: 'Comment s’entraîner',
    accueilEtapes: [
      'Plan : apprenez d’abord les 31 étagères, une catégorie à la fois.',
      'Livres : dix nouveaux titres par jour, revus au bon moment, avec la vraie couverture.',
      'Chrono : quand ça rentre, testez-vous contre la montre.',
    ],
    accueilBouton: 'Compris',
    indiceSaisie: 'Tapez 1 ou 2, puis la lettre, ou cliquez la carte.',
    carteLibelle: 'Carte',
    carteOptions: { noms: 'Noms', identifiants: 'Identifiants', muette: 'Muette' },
    identifiant: 'Identifiant',
    cliquezCarte: 'Cliquez son emplacement sur la carte vierge.',
    entrainement: { session: 'Session du jour', libre: 'Libre' },
    affichage: { complet: 'Livre et titre', couverture: 'Couverture seule', tranche: 'Tranche seule' },
    affichageLibelle: 'Affichage',
    aRevoir: (n: number) => `${n} à revoir`,
    nouveauxRestants: (n: number) => `${n} nouveau${n > 1 ? 'x' : ''} aujourd’hui`,
    sessionTerminee: 'Session du jour terminée.',
    prochainRetour: (minutes: number) =>
      minutes < 60
        ? `Prochain livre à revoir dans ${Math.max(1, minutes)} min.`
        : `Prochain livre à revoir dans ${Math.round(minutes / 60)} h.`,
    plusDeNouveaux: (n: number) => `${n} nouveaux de plus`,
    passerEnLibre: 'Entraînement libre',
    cible: (sections: string[]) => `Entraînement ciblé : ${sections.join(', ')}`,
    quitterCible: 'Quitter',
    categorie: 'Catégorie',
    titreLivre: 'Titre',
    serieDe: (n: number) => `Série de ${n} tomes`,
    exact: (attendu: string, categorie: string) => `Exact : ${attendu} (${categorie})`,
    faute: (choisi: string, attendu: string, categorie: string) =>
      `Non, ${choisi} : c’était ${attendu} (${categorie})`,
    exactTomes: (attendu: string) => `Exact : ${attendu} tomes`,
    fauteTomes: (choisi: string, attendu: string) => `Non, ${choisi} : c’était ${attendu} tomes`,
    motsCles: 'Mots-clés',
    entreePourContinuer: 'Entrée pour continuer',
    continuer: 'Continuer',
    record: 'Record',
    aucun: 'aucun',
    lancer: 'Lancer',
    relancer: 'Relancer',
    longueur: 'Longueur',
    chronoConsigne: (n: number, penalite: number) => `${n} livres, +${penalite} s par faute`,
    chronoTitre: (i: number, n: number) => `Livre ${i}/${n}`,
    fautes: (n: number) => `${n} faute${n > 1 ? 's' : ''}`,
    termine: 'Terminé en',
    score: 'score',
    raccourcis:
      'Clavier : 1 ou 2 puis la lettre de l’étagère (sur un seul étage, la lettre suffit). Échap annule.',
    raccourcisTomes: 'Clavier : 3, 5 ou 1 (pour 10).',
    conseilTomes:
      'En speedrun, les séries de 3 tomes rapportent les points de compétence le plus vite : ce sont les titres à connaître en priorité.',
    carte: 'Plan de la bibliothèque',
    zoomCarte: 'Agrandir',
    maitrise: 'Maîtrise par étagère',
    planSu: 'plan su',
    confusions: 'Vos confusions',
    confusionsVide: 'Aucune confusion enregistrée pour l’instant.',
    fois: (n: number) => `${n} fois`,
    sEntrainer: 'S’entraîner',
    exporter: 'Exporter la progression',
    importer: 'Importer',
    importe: 'Progression importée.',
    importRate: 'Fichier illisible.',
    effacer: 'Effacer la progression',
    confirmerEffacer: 'Effacer toute la progression et les records ?',
    credits:
      'Outil de fans, gratuit, sans lien avec le studio. Titres, couvertures et carte appartiennent aux auteurs du jeu.',
    suggestions: 'Suggestions et signalements',
    creePar: 'Créé par',
    contact: 'contact via les issues GitHub',
    sourcesTitre: 'Sources et remerciements',
    sourcesIntro: 'Cet outil n’existerait pas sans le travail de ces personnes :',
    sources: [
      {
        libelle: 'Full book visual study guide (Arcane Librarian Book Catalogue)',
        url: 'https://www.speedrun.com/Librarian_Tidy_Up_the_Arcane_Library/guides/dlw2n',
        detail: 'par coolsa, la feuille Google d’où viennent les 400 titres, leurs étagères, leurs séries et les images des livres, photographiés un à un en jeu',
      },
      {
        libelle: 'Complete Guide (Map, All Floors, Shelves & Book Lists)',
        url: 'https://steamcommunity.com/sharedfiles/filedetails/?id=3726876824',
        detail: 'par Monki, le guide Steam dont vient la carte des deux étages',
      },
      {
        libelle: 'Speedrun trainer de Le N',
        url: 'https://tutal-speedrun.nobodev.fr',
        detail: 'par Le N, l’autre entraîneur du jeu, qui a ouvert la voie ; essayez-le aussi',
      },
      {
        libelle: 'Librarian Book Locations Guide',
        url: 'https://librariangame.com/book-locations/',
        detail: 'par Librarian Game Guide, les mots-clés et les notes par catégorie affichés à la faute',
      },
      {
        libelle: 'Librarian: Tidy Up the Arcane Library!',
        url: 'https://store.steampowered.com/app/4197610/',
        detail: 'le jeu, sur Steam',
      },
    ],
    langue: 'English',
  },
  en: {
    titre: 'Arcane Library Shelf Trainer',
    sousTitre: 'Learn every book’s shelf and series size, for speedrunning',
    jeu: 'Librarian: Tidy Up the Arcane Library!',
    jaugePlan: 'Map',
    jaugeLivres: 'Books',
    jaugeTomes: 'Volumes',
    jaugeEtageres: 'Shelves',
    etagere: 'Shelf',
    exactEtagere: (titre: string) => `Correct: “${titre}”`,
    fauteEtagere: (titreChoisi: string, section: string, categorie: string, titreAttendu: string) =>
      `No: “${titreChoisi}” is in ${section} (${categorie}). It was “${titreAttendu}”`,
    raccourcisEtagere: 'Keyboard: 1 to 4.',
    modes: {
      plan: { nom: 'Map', aide: 'A category: which shelf?' },
      situer: { nom: 'Locate', aide: 'A shelf code: where is it, from memory?' },
      livres: { nom: 'Books', aide: 'A book: which shelf?' },
      etagere: { nom: 'Shelf', aide: 'A shelf: which of these books belongs there?' },
      tomes: { nom: 'Volumes', aide: 'A book: how many volumes in the series?' },
      chrono: { nom: 'Timer', aide: 'Books against the clock' },
    },
    filtres: { tous: 'Both floors', '1': 'Floor 1', '2': 'Floor 2' },
    filtreTomes: 'Series',
    tousLesTomes: 'All',
    tomesPastille: (n: number) => `${n} volumes`,
    sep: ': ',
    enJeu: 'In game',
    accueilTitre: 'How to practice',
    accueilEtapes: [
      'Map: learn the 31 shelves first, one category at a time.',
      'Books: ten new titles a day, reviewed at the right time, with the real cover.',
      'Timer: once it sticks, test yourself against the clock.',
    ],
    accueilBouton: 'Got it',
    indiceSaisie: 'Type 1 or 2, then the letter, or click the map.',
    carteLibelle: 'Map',
    carteOptions: { noms: 'Names', identifiants: 'Codes', muette: 'Blank' },
    identifiant: 'Shelf code',
    cliquezCarte: 'Click where it is on the blank map.',
    entrainement: { session: 'Today’s session', libre: 'Free practice' },
    affichage: { complet: 'Book and title', couverture: 'Cover only', tranche: 'Spine only' },
    affichageLibelle: 'Show',
    aRevoir: (n: number) => `${n} to review`,
    nouveauxRestants: (n: number) => `${n} new today`,
    sessionTerminee: 'Today’s session is done.',
    prochainRetour: (minutes: number) =>
      minutes < 60
        ? `Next review in ${Math.max(1, minutes)} min.`
        : `Next review in ${Math.round(minutes / 60)} h.`,
    plusDeNouveaux: (n: number) => `${n} more new books`,
    passerEnLibre: 'Free practice',
    cible: (sections: string[]) => `Focused practice: ${sections.join(', ')}`,
    quitterCible: 'Leave',
    categorie: 'Category',
    titreLivre: 'Title',
    serieDe: (n: number) => `${n}-volume series`,
    exact: (attendu: string, categorie: string) => `Correct: ${attendu} (${categorie})`,
    faute: (choisi: string, attendu: string, categorie: string) =>
      `No, ${choisi}: it was ${attendu} (${categorie})`,
    exactTomes: (attendu: string) => `Correct: ${attendu} volumes`,
    fauteTomes: (choisi: string, attendu: string) => `No, ${choisi}: it was ${attendu} volumes`,
    motsCles: 'Keywords',
    entreePourContinuer: 'Enter to continue',
    continuer: 'Continue',
    record: 'Best',
    aucun: 'none',
    lancer: 'Start',
    relancer: 'Run again',
    longueur: 'Length',
    chronoConsigne: (n: number, penalite: number) => `${n} books, +${penalite} s per mistake`,
    chronoTitre: (i: number, n: number) => `Book ${i}/${n}`,
    fautes: (n: number) => `${n} mistake${n > 1 ? 's' : ''}`,
    termine: 'Finished in',
    score: 'score',
    raccourcis:
      'Keyboard: 1 or 2, then the shelf letter (on a single floor, the letter alone). Esc clears.',
    raccourcisTomes: 'Keyboard: 3, 5 or 1 (for 10).',
    conseilTomes:
      'In speedruns, 3-volume series earn skill points fastest: those are the titles to learn first.',
    carte: 'Library map',
    zoomCarte: 'Zoom',
    maitrise: 'Mastery per shelf',
    planSu: 'map known',
    confusions: 'Your confusions',
    confusionsVide: 'No confusion recorded yet.',
    fois: (n: number) => `${n} time${n > 1 ? 's' : ''}`,
    sEntrainer: 'Practice',
    exporter: 'Export progress',
    importer: 'Import',
    importe: 'Progress imported.',
    importRate: 'Unreadable file.',
    effacer: 'Reset progress',
    confirmerEffacer: 'Erase all progress and records?',
    credits:
      'Free fan-made tool, not affiliated with the studio. Titles, covers and map belong to the game’s authors.',
    suggestions: 'Suggestions and reports',
    creePar: 'Made by',
    contact: 'contact through GitHub issues',
    sourcesTitre: 'Sources and thanks',
    sourcesIntro: 'This tool would not exist without the work of these people:',
    sources: [
      {
        libelle: 'Full book visual study guide (Arcane Librarian Book Catalogue)',
        url: 'https://www.speedrun.com/Librarian_Tidy_Up_the_Arcane_Library/guides/dlw2n',
        detail: 'by coolsa, the spreadsheet behind the 400 titles, their shelves, series sizes and book images, each photographed in game',
      },
      {
        libelle: 'Complete Guide (Map, All Floors, Shelves & Book Lists)',
        url: 'https://steamcommunity.com/sharedfiles/filedetails/?id=3726876824',
        detail: 'by Monki, the Steam guide the two-floor map comes from',
      },
      {
        libelle: 'Speedrun trainer by Le N',
        url: 'https://tutal-speedrun.nobodev.fr',
        detail: 'by Le N, the other trainer for this game, which came first; try it too',
      },
      {
        libelle: 'Librarian Book Locations Guide',
        url: 'https://librariangame.com/book-locations/',
        detail: 'by Librarian Game Guide, the per-category keywords and notes shown after a mistake',
      },
      {
        libelle: 'Librarian: Tidy Up the Arcane Library!',
        url: 'https://store.steampowered.com/app/4197610/',
        detail: 'the game, on Steam',
      },
    ],
    langue: 'Français',
  },
}
