// Tous les textes de l'interface, en français et en anglais. Les titres, catégories
// et identifiants d'étagères restent ceux du jeu (anglais) dans les deux langues.

export type Langue = 'fr' | 'en'

export const TEXTES = {
  fr: {
    titre: 'Arcane Library Shelf Trainer',
    sousTitre: 'Apprenez l’étagère et la série de chaque livre, pour le speedrun',
    jeu: 'Librarian: Tidy Up the Arcane Library!',
    jaugePlan: 'Plan',
    jaugeLivres: 'Livres',
    jaugeTomes: 'Tomes',
    jaugeEtageres: 'Étagères',
    etagere: 'Étagère',
    exactEtagere: (titre: string) => `Exact : « ${titre} »`,
    fauteEtagere: (titreChoisi: string, section: string, categorie: string, titreAttendu: string) =>
      `Non : « ${titreChoisi} » est en ${section} — ${categorie}. C’était « ${titreAttendu} »`,
    raccourcisEtagere: 'Clavier : 1 à 4.',
    modes: {
      plan: { nom: 'Plan', aide: 'Une catégorie : quelle étagère ?' },
      livres: { nom: 'Livres', aide: 'Un livre : quelle étagère ?' },
      etagere: { nom: 'Étagère', aide: 'Une étagère : lequel de ces livres y est rangé ?' },
      tomes: { nom: 'Tomes', aide: 'Un livre : combien de tomes dans la série ?' },
      chrono: { nom: 'Chrono', aide: 'Des livres contre la montre' },
    },
    filtres: { tous: 'Les deux étages', '1': 'Étage 1', '2': 'Étage 2' },
    filtreTomes: 'Séries',
    tousLesTomes: 'Toutes',
    tomesPastille: (n: number) => `${n} tomes`,
    nomsSurCarte: 'Noms des catégories sur la carte',
    entrainement: { session: 'Session du jour', libre: 'Libre' },
    affichage: { complet: 'Livre et titre', couverture: 'Couverture seule', tranche: 'Tranche seule' },
    affichageLibelle: 'Affichage',
    aRevoir: (n: number) => `${n} à revoir`,
    nouveauxRestants: (n: number) => `${n} nouveau${n > 1 ? 'x' : ''} aujourd’hui`,
    sessionTerminee: 'Session du jour terminée.',
    prochainRetour: (minutes: number) =>
      minutes < 60
        ? `Prochain livre à revoir dans ${Math.max(1, minutes)} min.`
        : `Prochain livre à revoir dans ${Math.round(minutes / 60)} h.`,
    plusDeNouveaux: (n: number) => `${n} nouveaux de plus`,
    passerEnLibre: 'Entraînement libre',
    cible: (sections: string[]) => `Entraînement ciblé : ${sections.join(', ')}`,
    quitterCible: 'Quitter',
    categorie: 'Catégorie',
    titreLivre: 'Titre',
    serieDe: (n: number) => `Série de ${n} tomes`,
    exact: (attendu: string, categorie: string) => `Exact : ${attendu} — ${categorie}`,
    faute: (choisi: string, attendu: string, categorie: string) =>
      `Non, ${choisi} : c’était ${attendu} — ${categorie}`,
    exactTomes: (attendu: string) => `Exact : ${attendu} tomes`,
    fauteTomes: (choisi: string, attendu: string) => `Non, ${choisi} : c’était ${attendu} tomes`,
    motsCles: 'Mots-clés',
    entreePourContinuer: 'Entrée pour continuer',
    continuer: 'Continuer',
    record: 'Record',
    aucun: 'aucun',
    lancer: 'Lancer',
    relancer: 'Relancer',
    longueur: 'Longueur',
    chronoConsigne: (n: number, penalite: number) => `${n} livres, +${penalite} s par faute`,
    chronoTitre: (i: number, n: number) => `Livre ${i}/${n}`,
    fautes: (n: number) => `${n} faute${n > 1 ? 's' : ''}`,
    termine: 'Terminé en',
    score: 'score',
    raccourcis:
      'Clavier : 1 ou 2 puis la lettre de l’étagère (sur un seul étage, la lettre suffit). Échap annule.',
    raccourcisTomes: 'Clavier : 3, 5 ou 1 (pour 10).',
    conseilTomes:
      'En speedrun, les séries de 3 tomes rapportent les points de compétence le plus vite : ce sont les titres à connaître en priorité.',
    carte: 'Plan de la bibliothèque',
    maitrise: 'Maîtrise par étagère',
    planSu: 'plan su',
    confusions: 'Vos confusions',
    confusionsVide: 'Aucune confusion enregistrée pour l’instant.',
    fois: (n: number) => `${n} fois`,
    sEntrainer: 'S’entraîner',
    exporter: 'Exporter la progression',
    importer: 'Importer',
    importe: 'Progression importée.',
    importRate: 'Fichier illisible.',
    effacer: 'Effacer la progression',
    confirmerEffacer: 'Effacer toute la progression et les records ?',
    credits:
      'Outil de fans, gratuit. Titres, couvertures et carte appartiennent aux auteurs du jeu ; carte d’après le guide Steam « Complete Guide (Map, All Floors, Shelves & Book Lists) ».',
    langue: 'English',
  },
  en: {
    titre: 'Arcane Library Shelf Trainer',
    sousTitre: 'Learn every book’s shelf and series size, for speedrunning',
    jeu: 'Librarian: Tidy Up the Arcane Library!',
    jaugePlan: 'Map',
    jaugeLivres: 'Books',
    jaugeTomes: 'Volumes',
    jaugeEtageres: 'Shelves',
    etagere: 'Shelf',
    exactEtagere: (titre: string) => `Correct: “${titre}”`,
    fauteEtagere: (titreChoisi: string, section: string, categorie: string, titreAttendu: string) =>
      `No: “${titreChoisi}” is in ${section} — ${categorie}. It was “${titreAttendu}”`,
    raccourcisEtagere: 'Keyboard: 1 to 4.',
    modes: {
      plan: { nom: 'Map', aide: 'A category: which shelf?' },
      livres: { nom: 'Books', aide: 'A book: which shelf?' },
      etagere: { nom: 'Shelf', aide: 'A shelf: which of these books belongs there?' },
      tomes: { nom: 'Volumes', aide: 'A book: how many volumes in the series?' },
      chrono: { nom: 'Timer', aide: 'Books against the clock' },
    },
    filtres: { tous: 'Both floors', '1': 'Floor 1', '2': 'Floor 2' },
    filtreTomes: 'Series',
    tousLesTomes: 'All',
    tomesPastille: (n: number) => `${n} volumes`,
    nomsSurCarte: 'Category names on the map',
    entrainement: { session: 'Today’s session', libre: 'Free practice' },
    affichage: { complet: 'Book and title', couverture: 'Cover only', tranche: 'Spine only' },
    affichageLibelle: 'Show',
    aRevoir: (n: number) => `${n} to review`,
    nouveauxRestants: (n: number) => `${n} new today`,
    sessionTerminee: 'Today’s session is done.',
    prochainRetour: (minutes: number) =>
      minutes < 60
        ? `Next review in ${Math.max(1, minutes)} min.`
        : `Next review in ${Math.round(minutes / 60)} h.`,
    plusDeNouveaux: (n: number) => `${n} more new books`,
    passerEnLibre: 'Free practice',
    cible: (sections: string[]) => `Focused practice: ${sections.join(', ')}`,
    quitterCible: 'Leave',
    categorie: 'Category',
    titreLivre: 'Title',
    serieDe: (n: number) => `${n}-volume series`,
    exact: (attendu: string, categorie: string) => `Correct: ${attendu} — ${categorie}`,
    faute: (choisi: string, attendu: string, categorie: string) =>
      `No, ${choisi}: it was ${attendu} — ${categorie}`,
    exactTomes: (attendu: string) => `Correct: ${attendu} volumes`,
    fauteTomes: (choisi: string, attendu: string) => `No, ${choisi}: it was ${attendu} volumes`,
    motsCles: 'Keywords',
    entreePourContinuer: 'Enter to continue',
    continuer: 'Continue',
    record: 'Best',
    aucun: 'none',
    lancer: 'Start',
    relancer: 'Run again',
    longueur: 'Length',
    chronoConsigne: (n: number, penalite: number) => `${n} books, +${penalite} s per mistake`,
    chronoTitre: (i: number, n: number) => `Book ${i}/${n}`,
    fautes: (n: number) => `${n} mistake${n > 1 ? 's' : ''}`,
    termine: 'Finished in',
    score: 'score',
    raccourcis:
      'Keyboard: 1 or 2, then the shelf letter (on a single floor, the letter alone). Esc clears.',
    raccourcisTomes: 'Keyboard: 3, 5 or 1 (for 10).',
    conseilTomes:
      'In speedruns, 3-volume series earn skill points fastest: those are the titles to learn first.',
    carte: 'Library map',
    maitrise: 'Mastery per shelf',
    planSu: 'map known',
    confusions: 'Your confusions',
    confusionsVide: 'No confusion recorded yet.',
    fois: (n: number) => `${n} time${n > 1 ? 's' : ''}`,
    sEntrainer: 'Practice',
    exporter: 'Export progress',
    importer: 'Import',
    importe: 'Progress imported.',
    importRate: 'Unreadable file.',
    effacer: 'Reset progress',
    confirmerEffacer: 'Erase all progress and records?',
    credits:
      'Free fan-made tool. Titles, covers and map belong to the game’s authors; map after the Steam guide “Complete Guide (Map, All Floors, Shelves & Book Lists)”.',
    langue: 'Français',
  },
}
